---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: centos9
    box: generic/centos9s
    memory: 12288
    cpus: 4
    interfaces:
      - network_name: private_network
        ip: 192.168.50.20
    #provider_raw_config_args:
    #  - "customize [ 'modifyvm', :id, '--natdnshostresolver1', 'on' ]"

provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
  log: true
verifier:
  name: ansible
