name: molecule

on: [push]

jobs:
  molecule:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install depenencies
      run: |
        brew update
        brew install python@3
        brew install vagrant
        brew install libvirt
        pip install ansible libvirt-python python-vagrant molecule molecule-vagrant
    - name: Run molecule
      run: |
        cd myrole
        molecule test

    
