name: molecule

on: [push]

jobs:
  molecule:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install depenencies
      run: |
        brew update
        brew install virtualbox
        brew install vagrant
        python3 -m pip install ansible python-vagrant molecule molecule-vagrant
      env:
        HOMEBREW_NO_INSTALL_CLEANUP: 1
    - name: Run molecule
      run: |
        cd myrole
        molecule test

    
