name: molecule

on: [push]

jobs:
  molecule:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - uses: gofrolist/molecule-action@v2
      with:
        molecule_working_dir: myrole
        molecule_args: --driver vagrant
      env:
        ANSIBLE_FORCE_COLOR: '1'

    
