name: molecule

on: [push]

jobs:
  molecule:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Install depenencies
      run: |
        brew update
        brew install vagrant
        brew install libvirt
        brew services start libvirt
        virsh -c "qemu:///session" capabilities
        exit 1
        python3 -m pip install ansible libvirt-python python-vagrant molecule molecule-vagrant
        vagrant plugin install vagrant-libvirt
    - name: Run molecule
      run: |
        cd myrole
        molecule test

    
